import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <title>Mwitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS9e5vPI_ea_YVz2HNBp7OcOwnaUa4yR7mz4hFVxz3FIa7fdpg3" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
